# Generated by Django 5.2.6 on 2025-09-05 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_otp_attempts_order_otp_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="otp_attempts",
        ),
        migrations.RemoveField(
            model_name="order",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="otp_expires_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="otp_hash",
        ),
        migrations.RemoveField(
            model_name="order",
            name="otp_salt",
        ),
    ]
